server:
    port: 8081
spring:
    application:
        name: Driveluxe
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Samy1!2@
        url: jdbc:mysql://localhost:3306/Driveluxe
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        open-in-view: false
springdoc:
    swagger-ui:
        path: /swagger-ui.html
